version: '2'

services:
  interfaceeae:
    image: aoehmich/interfaceEAE:latest
    hostname: interfaceeae
    stdin_open: true
    tty: true
    depends_on:
    - mongo
    - worker1
    - worker2
    ports:
    - "8443:8443"
  worker1:
    image: aoehmich/workerEAE:latest
    container_name: worker1
    hostname: worker1
    stdin_open: true
    tty: true
  worker2:
    image: aoehmich/workerEAE:latest
    container_name: worker2
    hostname: worker2
    stdin_open: true
    tty: true
  mongo-initialize:
    image: aoehmich/mongoEAE:latest
    depends_on:
    - mongo
  mongo:
    image: mongo:3.4.0
    ports:
    - "27017:27017"
