version: '2'

services:
  mongodb:
    image: mongo:3.4.0
    restart: unless-stopped
    port:
    - "127.0.0.1:27017:27017"
  interfaceEAE:
    image: aoehmichen/interfaceEAE:latest
    restart: unless-stopped
    port:
    - "22:22"
    - "8443:8443"
    - "16322:16322"
    - "16323:16323"
    - "16324:16324"
    - "16324:16325"
    depends_on:
    - mongodb